-- Agium Sales Dashboard — seed data (554 contacten + 14 events)
-- Voer dit uit NA schema.sql, éénmalig, in de Supabase SQL Editor.

-- ============ EVENTS ============
insert into events (name, event_date, sort_order) values
  ('10 Feb | ERP Sessie', '2026-02-10', 0),
  ('20 Mar | T&L Lunch', '2026-03-20', 1),
  ('24 Mar | CFO Diner', '2026-03-24', 2),
  ('26 Mar | SSC Sessie', '2026-03-26', 3),
  ('CFO Top 14 april', '2026-04-14', 4),
  ('15 Apr | PC Sessie', '2026-04-15', 5),
  ('17 Apr | Golfclinic', '2026-04-17', 6),
  ('10 Mei | Ajax-Utrecht', '2026-05-10', 7),
  ('15 Mei | TPM Delft', '2026-05-15', 8),
  ('19 Mei | TPM Breda', '2026-05-19', 9),
  ('21 Mei | CFO Open', '2026-05-21', 10),
  ('26 Jun | CFO Lunch', '2026-06-26', 11),
  ('02 Jul | Future CFO', '2026-07-02', 12),
  ('Boekactie', NULL, 999999)
on conflict (name) do nothing;

-- ============ CONTACTS ============
insert into contacts (event_name, aanwezig, organisatie, contact, functie, bm, actie_voor, actie_na, propositie, response, afspraak, aanvraag, klant_type, opmerkingen) values
  ('10 Feb | ERP Sessie', 'Ja', 'Euro Pool System', 'Caspar van der Meer', 'Finance Director EPS Europe', 'Arno', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Opvolgen mail", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Heineken Nederland', 'Filip Forceville', 'GPO Finance', 'Michael', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "5-3 michael koffie gedronken", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', '3M Nederland', 'Jan Kuiper', 'Director Global Process & CI RTR  / 3M', 'Arno', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Komt terug op ev afpsraak Ernst", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Eet gemak Groep', 'Jan-Pieter Ebben', 'CFO', 'Arno', 'Mail', NULL, 'ABC', NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Eind 2027 opportuun", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'wirefinanceconsultancy.nl', 'Reinier Wisse', 'CFO', 'Arno', 'Call', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Afspraak gemaakt", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Rail Innovators Group', 'Dennis Ardon', 'Group Financial Controller', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', '', 'Sebastiaan Stipdonk', 'CFO', 'Joost', 'Visit', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Ernst is langs geweest voor een opportuny", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Sandoz', 'Chiel Schoevaars', 'Head FRA and Tax', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Michael plannen meeting KOMT NAAR DINER 24 maart", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Woningnet Basisdiensten B.V.', 'Dezso Racz', 'CFO', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "2-2 mail gestuurd ter voorbereiding", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Adapa', 'Herman Weber', 'Group Controller', 'Michael', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "koffie later dit jaar", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Mecanoo', 'Maarten Postma', 'CFO', 'Joost', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Mail + Visit gepland voor 19-2", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Aspen Pharma', 'Pieter Vink', 'CFO', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "2-2 mail gestuurd ter voorbereiding", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'APOLLO GROUP', 'Geert-Jan Alofs', 'CFO', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Michael plannen meeting", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Xelion', 'Irvin Wekking', 'Finance Manager', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Dolmans Groep B.V.', 'Marcel van Ede', 'groepscontroller', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Michael plannen meeting", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Royal J.M. de Jong Group', 'Marcel Van Rosmalen', 'CFO', 'Marc', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "25-3 gaan we langs", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'LBC Rotterdam B.V.', 'patrick kooijmans', 'director finance', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Komt naar Logistiek lunch 20-3", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Oilinvest Group', 'PETER KOEDIJK', 'Group CFO', 'Marc', NULL, 'Visit', 'ABS', NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Lead via Marc", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'VolkerRail B.V.', 'Wilfred Bonouvrie', 'Manager FSSC', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', '', 'Emile Goossens', 'CFO', 'Max', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'LINKIT', 'Fred Kater', 'CFO', 'Max', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Everfield', 'Harco Zomerman', 'Director Financial Reporting & Analysis', 'Max', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', '', 'Jotte van Ierland', 'Verandermanager', 'Max', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Van der Ende', 'Koen Eijkemans', 'CFO', 'Max', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Houtgroep van Drimmelen', 'Marcel Wijmans', 'controller', 'Max', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'LINKIT', 'Max de Meijer', 'Business Controller', 'Max', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'MartinStolze', 'Marvin de Klerk', 'CFO', 'Roberto', 'Mail', 'Call', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Aanvraag  voor Roberto 3-3", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', '', 'Monique Dijkhuizen', 'Finance (verander) manager', 'Max', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Hametha BV | Standic, De Haan Tankstations & MAES Energy & Mobility', 'Maarten Berends', 'CFO', 'Max', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Michael plannen meeting KRIJG NIET ECHT REACTIE", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Laurens', 'Ben Jalhay', 'Controller', 'Michael', 'Mail', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "nog geen reactie ", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'CM.com Netherlands BV', 'Frank Theunis', 'Finance Director', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "komt niets uit", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Megagroup', 'Michiel Baarle', 'Eigenaar', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "heeft gereageerd", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Koninklijke Auris Groep', 'Adrie Lupker', 'Teamleider Financiën', 'Roberto', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Al jaren klant", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Donghua International BV', 'Thomas de Haas', 'Controller', 'Michael', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "19-3 Koffie Michael ", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Van Caem Klerks Group', 'Wilco Lek', 'controller', 'Roberto', 'Mail', 'Call', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Call gehad, MvdS aangehaakt voor werving, heeft nu geen baan", "origin": "origineel"}]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Last Mile Solutions B.V.', 'Bouke Boumans', 'Financial Controller', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Uzimet B.V.', 'Hans van der Goes', 'Finance director', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Nationale Nederlanden', 'Michael Coers', 'Head of Management Reporting', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'iHub', 'Pieter Coens', 'Directeur Bedrijfvoering', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'VDfinancialservices', 'Richard van Duijn', 'CFO', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', NULL, 'Yvar Van Weenen', 'Finance Manager', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', 'Kees Smit', 'Wilma de Goede', 'CFO', 'Michael', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Nee', 'Philips', 'Wouter Mul', 'CFO', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Feb | ERP Sessie', 'Ja', NULL, 'Marcel van Stipdonk', 'CFO', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-02-10", "text": "Michael plannen meeting", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', 'Nee', 'CEVA Logistics', 'Martijn Melissant', NULL, 'Olaf', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "Gelderland", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', NULL, 'Rail innovators Group', 'Philipp Belle', NULL, 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "Noord-Holland", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', NULL, 'Port of Rotterdam', 'Teije Smittenaar', NULL, 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "Zuid-Holland", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', NULL, 'DP World', 'Robin Fennis', NULL, 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "Noord-Holland", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', NULL, 'BosDaalen', 'Lerno Duwel', NULL, 'Arno', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "Zuid-Holland", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', NULL, 'LBC Tankterminals', 'Patrick Kooijmans', NULL, 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "Zuid-Holland", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', 'Nee', 'FarmTrans', 'Winfred van Houwelingen', NULL, 'Olaf', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "Is gestopt, maar drinken wel een kop koffie", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', NULL, ' i+solutions', 'Claudia de Smit', NULL, 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "Utrecht", "origin": "origineel"}]'::jsonb),
  ('20 Mar | T&L Lunch', NULL, 'Cencora', 'Ilona  Krjukova', NULL, 'Olaf', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-20", "text": "brabant", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', 'Nee', 'Unica', 'Ron van Laar', 'CFO', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Van Leeuwen Buizen', 'Vincent Geerts', 'CFO', 'Olaf', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "recepten mailen", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Totalenergies-Corbion', 'Chiel Rietvelt', 'CFO', 'Sander', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "Michael Gemaild voor intro Sander", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Van Mossel Autogroep', 'Erik van Loon', 'CFO', 'Olaf', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "recepten verstuurd", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Mediq', 'Linda Weijters', 'CFO', 'Marc', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "Michael mail gestuurd voor Marc en schiet op agium sessie", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Hamiplant', 'Titus van Wijngaarden', 'CFO', 'Roberto', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "Michael gemaild met joost roberto in cc. roberto gaat binnenkort langs", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'VTTI b.v.', 'Pan van Geffen', 'Deputy CFO', 'Olaf', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "net voor diner langs geweest", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Albert Heijn', 'Simon van Rijn', 'CFO', 'Joost', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "Michael gemaild ", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Louwman Groep', 'Lisanne Rijnders', 'CFO Retail', 'Sander', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "michael Koffie plannen mei ", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Talpa Network', 'Alexander Kousbroek', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "Joost direct", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'Hogeschool INHolland Delft', 'Christel Buis', 'CFO', 'Arno', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "Michael mail gestuurd voor afspraak arno marc opleiden", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'West Coast Supply Group', 'Stijn Schneider', 'CFO', 'Roberto', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "Michael heeft gemaild Roberto CC", "origin": "origineel"}]'::jsonb),
  ('24 Mar | CFO Diner', NULL, 'N-Sea', 'Ann Porte', 'CFO  ', 'Marc', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-24", "text": "staat afspraak 30-3 samen met Olaf en recepten verstuurd", "origin": "origineel"}]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'Movares', 'Conny Vermeulen', NULL, 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'Vanderlande', 'Joris Brands', NULL, 'Max', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'A.S. Watson', 'George Keverkamp', NULL, 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'Sweco', 'Rina Pieters-Ong', NULL, 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'SGS', 'Richard Oostrom', NULL, 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'PostNL', 'Gerrit Elsinga', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'Nippon', 'Edward Patty', NULL, 'Olaf', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'Van Oord', 'Robert Giezen', NULL, 'Olaf', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'Boskalis', 'Bart-Jan Beerens', NULL, 'Max', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'Vopak', 'Jelmer Vos', NULL, 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Ja', 'DNV', 'Xander van der Meijden', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Nee', 'Transdev', 'Rik Klinkenbijl', NULL, 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', 'Ja', 'Facilicom', 'Marcel van der Plas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', NULL, 'Universiteit Leiden', 'René Preenen', NULL, 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-03-26", "text": "Tender volgt in Q2", "origin": "origineel"}]'::jsonb),
  ('26 Mar | SSC Sessie', NULL, 'GKN Aerospace', 'Wesley Nijssen', NULL, 'Max', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', NULL, 'Wim Boer', 'Brocacef', NULL, 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', NULL, 'Louwman Group', 'Arhur Willenborg', NULL, 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Mar | SSC Sessie', NULL, 'Brocacef', 'Nathan Bijl', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'ABB', 'Ties Verbruggen', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Friso Wolters', 'CFO ACT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Tom Poppelaars', 'Finance Director EMEA ACT', 'Michael', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-14", "text": "uitgenodigd Agium Summit", "origin": "origineel"}]'::jsonb),
  ('CFO Top 14 april', NULL, 'Adapa', 'Herman Weber', 'VP Finance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'AholdDelhaize', 'Joris Verheijen', 'VP Finance Operations', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Airtrade', 'Laurens Vonkeman', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Nobel', 'Koen Vermeulen', 'CFO Integrated Supply Chain Akzo', 'Michael', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-14", "text": "uitgenodigd Agium Summit", "origin": "origineel"}]'::jsonb),
  ('CFO Top 14 april', NULL, 'Osram', 'Ron Colen', 'CFO AMS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'ASML', 'Dennis Oostenenk', 'VP Finance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'ASML', 'Ron van', 'Workum Principal IT Security Consultant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'BV', 'Claudia Heger', 'CFO Atrium Agri', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Bakerij', 'Erik-Pieter Weerts', 'Finance Director Bacu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Belastingdienst', 'Peter Smink', 'DG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Solutions', 'Edmund Tenfelde', 'Vice-voorzitter Bollegraaf Recycling', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Byldis', 'Robyn-Lee Noble', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'C2Value', 'Jos Houben', 'Commissaris', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Centrient', 'Vincent Segers', 'CISO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'International', 'Pepijn Asselberghs', 'CFO Chrysal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Circreate', 'Koos Frowein', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Chance', 'Robert Smit', 'CFO Clifford', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CM.com', 'Frank Theunis', 'Finance Director', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Europe', 'Walter Woortman', 'CFO Collins Foods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Conclusion', 'Emiel van', 'Boxtel CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Cyclomedia', 'Rogier van', 'Wijk CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Damen', 'Marcel Oosterom', 'Financieel Directeur', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Heus', 'Martijn de', 'Nijs Treasurer De', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'DFG', 'Joost Gietelink', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'DHL', 'Gijsbert Burggraaf', 'CFO Benelux', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Realty', 'Pieter de', 'Bruijn VP EMEA Accounting Digital', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Dolmans', 'Bart Brouwer', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'EBN', 'Stijn van', 'Oeijen Group Controller', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Engie', 'Paul van', 'Hemmen CFO NL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Erasmus', 'Bert de', 'Groot Professor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Europe', 'Maurits Gaudesaboos', 'CFO Europe Euramax Mobility', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Fitz', 'Frank Sieben', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'ForFarmers', 'Koen Schuit', 'Group Finance Director', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Fujitsu', 'Peter Bleijenberg', 'FD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Hallo', 'Tom van', 'Dael Finance Director', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Robert Kuik', 'CFO Healthcare Brands', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Woningbouw', 'Richard Ossenblok', 'Financieel Directeur Heijmans', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'BV', 'Mirko de', 'Vos CFO Human Protection', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Logistics', 'Maurice de', 'Wilde CFO Husa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'HVC', 'Noortje Magis', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Inretail', 'Albert van', 'Bolderen Commissaris', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Interstellar', 'Farida Chotkan', 'CISO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Jumbo', 'Mark van', 'de Meulenhof Manager Internal Audit & Risk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Keygene', 'Robbert Oudendijk', 'VP Finance & Control', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Terminals', 'Patrick Kooijmans', 'FD LBC Tank', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Solutions', 'Frederik Stolwijk', 'CFO License Partners Cloud', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Lineage', 'Sophia van', 'Tol CFO Europe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Louwman', 'Robin Schluter', 'Financieel Directeur', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Florence van', 'der Kooij CFO Macademia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Marleen Kloppers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'MCB', 'Frank Peters', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Meeder', 'Joost Derickx', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Methanex', 'Aad Lagerburg', 'Finance Director', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Miele', 'Bas Ruts', 'Finance Director', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Jewellery', 'Vilmar Bliekendaal', 'CFO My', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Noordhoff', 'Robert de', 'Gier CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Sander Roosendaal', 'CFO Northwave', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'NS', 'Sander ter', 'Maat FD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'NTT', 'Jinny Lubbers', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'OCI', 'Rob Swarts', 'Group Controller', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'OCI', 'Mark van', 'der Heijden FD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Ass', 'Robertjan Dekker', 'CFO On That', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'P&P', 'Carlo Binken', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Joris Dierick', 'CFO PIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'PMSG', 'Norbert Smith', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'PreZero', 'Remko Walsweer', 'CFO NL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Notarissen', 'Martijn van', 'Veen CFO Quadrant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Philipp Belle', 'CFO Rail Innovators', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Hans van', 'den Bosch CFO Roll', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Co', 'Bastiaan Vaandrager', 'MD Rothschild &', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Geert-Jan Alofs', 'CFO Royal Apollo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'FloraHolland', 'David van', 'Mechelen CEO Royal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Han Stoop', 'CFO Salta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Shell', 'Hans Peter', 'van Arkel Country Controller', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Europe', 'Helena Bary', 'CFO Shell Energy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Energy', 'Geert Venderink', 'Group Controller SHV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Group', 'Leendert van', 'Reeuwijk CFO Speyzer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'SPNG', 'Frank van', 'Schie Non-executive', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Stedin', 'David Stolker', 'Manager Reporting', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Synthon', 'Angelo Cornelissen', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Holland', 'Rene van', '''t Hof CFO Tabs', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'TenneT', 'Sebastiaan Barlagen', 'CISO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Thales', 'Dirk Jan', 'de Boer Director Finance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Farm', 'Sander Overgaag', 'CFO The Flavour', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Connection', 'Maikel Veenboer', 'CFO The Floral', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Mobility', 'Raoul Gatzen', 'CFO Tier', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Vision', 'Ron van', 'Houten CFO TP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Triodos', 'Bilal Bas', 'Group Controller', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Unibail-Rodamco-Westfield', 'Gerard Sieben', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Unibarge', 'Sjoerd van', 'der Wulp CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Happen', 'Sjef van', 'Eck CFO Van', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Kempen', 'Frans Blom', 'Voorzitter Van Lanschot', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Groep', 'Richard Borsboom', 'CFO Vooruit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Woningnet', 'Dezso Racz', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'YourSurprise', 'Bram Buijs', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Zanders', 'Ewout West', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Camiel de', 'Vries', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Alewijnse', 'Carina Krastel', 'Hoek CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Commissaris', 'Daniëlle Foolen', 'Auteur / vml CFO en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Emile Hoekstra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Erkan Cagman', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Frank Hofman', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Frank Jonk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Jeroen Vos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Marnix Cornelius', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Wavin', 'Peter Nijman', 'Sr Manager Finance W Europe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Peter van', 'Dongen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'CFO', 'Ronald Diederiks', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Non-executive', 'Tjero Zomer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('CFO Top 14 april', NULL, 'Cyberalloy', 'Aernout Reijmer', 'CISO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Unica', 'Jeroen de Bree', 'Finance Director', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Prorail', 'Stanny Schapendonk', NULL, 'Arno', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "Mail gestuurd om een afspraak in te plannen", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Stedin', 'Steven Suiker', 'Directeur Control', 'Arno', 'Call', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "Afspraak richting de zomer bij Van Oord", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Bilfinger Industrial Services Nederland B.V.', 'Anton Brand', 'Manager Business Control', 'Arno', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Feadship', 'John Veldman', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Royal HaskoningDHV', 'Ronald Scholten', 'Business Line Controller Mobility & Infrastructure', 'Joost', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "niet met eten", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Mourik', 'Auke Droogh', 'Financieel Directeur', 'Marc', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Croonwolter&dros B.V.', 'Bart Kok', 'Divisiecontroller', 'Marc', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Strukton', 'Jacco Vos', 'Controller Projects', 'Marc', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Aton Projects', 'Jaco Robben', 'Manager F&C', 'Marc', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'TBI Holdings B.V.', 'Kimberley Reus', 'Financieel Directeur', 'Marc', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Havenbedrijf Rotterdam N.V.', 'Michiel Hoefnagels', 'Manager PMO', 'Marc', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'LBC Rotterdam B.V.', 'Niels van Bladeren', 'CFO', 'Marc', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'TNO', 'Paul ten Hout', 'Manager Unit Control', 'Marc', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'QBuild', 'Rene van elteren', 'Business Controller', 'Marc', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Croonwolter&dros B.V.', 'Stefan paulus', 'Business Controller', 'Marc', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Hes International BV', 'Patrick Dolle', 'Corporate Finance & Control', 'Max', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Baggermaatschappij Boskalis BV', 'Bart-Jan Beerens', 'General Manager FSSC', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'SPIE', 'Ido Swagerman', 'Divisie Controller Industry Services', 'Olaf', 'Call', 'Teams', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'RET', 'Kenrick Bremer', 'Concern Contoller', 'Olaf', 'Call', 'Teams', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Vanderlande Industries B.V.', 'Marcel Rongen', 'Controller', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Vanderlande Industries B.V.', 'Mark Roeters', 'Domain Controller', 'Olaf', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Hezelaer', 'Pim Flink', 'Head of Finance', 'Olaf', 'Call', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Clingendael', 'Erik Berwers', 'Project controller', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "geen dieet", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', NULL, 'Chane', 'Tim Osse', 'Manager Business Control', 'Sander', 'Mail', 'Visit', 'Deta', NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "Afspraak juni", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Cenosco', 'Wouter Heikens', 'CFO', 'Joost', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-15", "text": "Afspraak via teams wordt ingepland.", "origin": "origineel"}]'::jsonb),
  ('15 Apr | PC Sessie', 'Nee', 'Equans', 'Robert Melkert', 'Manager Finance', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'J.P. van Eesteren', 'Arjan de Looze', 'Financieel Directeur', 'Roberto', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "zi in gouda kan ook door Marc M opgepakt te worden", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Pathé', 'Bart Van Rooij', 'CFO', 'Sander', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', 'Nee', 'Geschillencommissie', 'Bas Luten', 'Directeur', 'Joost', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Brink''s', 'Berend Jan van der Wal', 'CFO', 'Joost', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Alliander', 'Camiel de Vries', 'Change manager', 'Olaf', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', 'Nee', 'VORM Ontwikkeling', 'Christiaan van Steenbergen', 'CFO', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'minezk.nl', 'Ellen Thijert', 'Coordinator', 'Olaf', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact, vrouw van bergman C Erik", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Amsterdam Commodities N.V.', 'Eric Smit', 'Director', 'Arno', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Foppen Seafood', 'Eric Taal', 'CFO', 'Joost', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'United Rentals', 'Erik Koenraads', 'CFO', 'Olaf', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Bergman Clinics', 'Erik Meester', 'Group Director Finance', 'Arno', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "als jij Arno geen contact hebt, kan ik hem bellen", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Kenbri', 'Frank Scholtes', 'CFO', 'Olaf', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', 'Nee', 'Ivory Accounting & Ivory Assurance Services', 'Gerard Hanssen', 'Partner', 'Sander', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'PFM Footfall intelligence', 'Goof Lawa', 'Finance Director', 'Olaf', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact, nieuwe baan bezig", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Monchy Food Company', 'Guido Bakker', 'Business unit controller', 'Sander', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "oude bekende van ons, hier net gestart", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Actief Werkt', 'Hans Damhuis', 'CFO', 'Olaf', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Randstad Groep Nederland', 'Hans van Slooten', 'CFO Randstad Group Belgium', 'Michael', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'McCain Foods Holland B.V.', 'Huub Tholhuijsen', 'Financieel Directeur', 'Olaf', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Nationale Nederlanden', 'Jaco vd Meer', 'Change Manager', 'Sander', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Edco', 'Leendert van Reeuwijk', 'CFO', 'Joost', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'SER Topvrouwen', 'Manon Quaedvlieg', 'CFO', 'Michael', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Jiffy Group', 'Martin Hes', 'CFO', 'Arno', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'MSO Group', 'Paul van der Zande', 'CFO', 'Olaf', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Rail Innovators Group', 'Philipp Belle', 'CFO', 'Joost', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', 'Nee', 'Digital Realty Trust Inc', 'Pieter de Bruijn', 'VP EMEA ACCOUNTING', 'Joost', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', 'Nee', 'Transavia Airlines C.V.', 'Pieter Wensveen', 'CFO', 'Joost', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Uva Amsterdam', 'Raymond Deenstra', 'Zzp er', 'Michael', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Spares in Motion', 'Thomas mattheussens', 'Cfo', 'Olaf', 'Call', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Interfood Holding BV', 'Vincent Almering', 'Global Derivatives Director', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Hollandia', 'Eric Verheul', 'CFO', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('17 Apr | Golfclinic', NULL, 'Hollandia', 'Corvin Janssen', 'Manager Projectcontol/Finance manager', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-04-17", "text": "goed in contact", "origin": "origineel"}]'::jsonb),
  ('10 Mei | Ajax-Utrecht', NULL, 'Parlevliet & vd Pas', 'Carlo Binken', 'CFO', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-10", "text": "Vooralsnog even rustig, verdere opvolging na de zomerperiode.", "origin": "origineel"}]'::jsonb),
  ('10 Mei | Ajax-Utrecht', NULL, 'VodafeZiggo', 'Ritchy Drost', 'CFO', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-10", "text": "T.z.t. weer lunch inplannen om te bedanken voor Ajax-Utrecht Event", "origin": "origineel"}]'::jsonb),
  ('10 Mei | Ajax-Utrecht', NULL, 'TBI', 'Emiel Roozen', 'CFO', 'Joost', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-10", "text": "27-8 afspraak samen met Marc Morgenland.", "origin": "origineel"}]'::jsonb),
  ('10 Mei | Ajax-Utrecht', NULL, 'Van Wijnen', 'Jaap Vos', 'CFO', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('10 Mei | Ajax-Utrecht', NULL, 'OnThatAss', 'RobertJan Dekker', 'CFO', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-10", "text": "Is afspraak gepland", "origin": "origineel"}]'::jsonb),
  ('10 Mei | Ajax-Utrecht', NULL, 'Pantar', 'Ben van der Knaap', 'CEO', 'Joost', 'Call', 'Visit ', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-10", "text": "Is afspraak gepland", "origin": "origineel"}]'::jsonb),
  ('10 Mei | Ajax-Utrecht', NULL, 'Jumbo', 'Hendrik-Jan Roel', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-10", "text": "Even geduld nog, opvolging na de zomer", "origin": "origineel"}]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'Woningnet', 'Dezso Racz', 'CFO', 'Marc', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'dmg.eu', 'Fedor van Mullem', 'COO', 'Olaf', 'Visit', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-15", "text": "afspraak ingepland", "origin": "origineel"}]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'Uzimet B.V.', 'Hans van der Goes', 'Finance Director/Managing Director', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'McDonalds', 'Inge Hamilton', 'Finance director', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'Universiteit Leiden', 'Karin van Klaveren', 'teamleider ASSC Financieel', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'Sodexo', 'Maarten Bronda', 'CFO', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-15", "text": "afpraak gehad", "origin": "origineel"}]'::jsonb),
  ('15 Mei | TPM Delft', NULL, NULL, 'Richard van Duijn', 'Interim CFO', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'McDonalds', 'Rik van Nimwegen', 'Sr. Transformation Manager', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'Plazapadel', 'Robert Melgerd', 'Nvt', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-15", "text": "is ook op Agium Open geweest", "origin": "origineel"}]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'Holland Food Service', 'Roy Janssen', 'Financieel Directeur', 'Olaf', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-15", "text": "afspraak ingepland", "origin": "origineel"}]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'Exact Software Nederland B.V.', 'Sander Smit', 'Finance Director', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('15 Mei | TPM Delft', NULL, 'Louwman Groep', 'Wouter Jelier', 'Transformatie  Directeur', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('19 Mei | TPM Breda', NULL, 'Erasmus University Rotterdam', 'Daniel Feenstra', 'Director Finance, Control & Risk', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-19", "text": "afspraak ingepland", "origin": "origineel"}]'::jsonb),
  ('19 Mei | TPM Breda', NULL, 'De Efteling BV', 'Denise Luijten', 'Procescontroller', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-19", "text": "afspraak ingepland", "origin": "origineel"}]'::jsonb),
  ('19 Mei | TPM Breda', NULL, 'Archipel Academy', 'Jack Swart', 'Finance Improvement Manager', 'Olaf', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-19", "text": "afspraak ingepland", "origin": "origineel"}]'::jsonb),
  ('19 Mei | TPM Breda', NULL, 'Houtgroep van Drimmelen', 'Marcel Wijmans', 'controller', 'Olaf', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-19", "text": "afspraak ingepland", "origin": "origineel"}]'::jsonb),
  ('19 Mei | TPM Breda', NULL, 'Gielissen Interiors', 'Robert van de Looij', 'senior business controller', 'Olaf', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-19", "text": "afspraak ingepland", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, '', 'Albert Hollema', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Croonwolter&dros B.V.', 'Angela van Rijn', 'Financieel directeur', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'ERA Contour', 'Antoine van Dongen', 'Financieel Directeur', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Bluewater Energie Services B.V.', 'Arjan van der Laan', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Maersk', 'Avijit Banerjee', 'Head of Business Control', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Pathé', 'Bart van Rooij', 'CFO', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Home Fashion Group', 'Bas Luten', 'Directeur', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "i.s.m. Joost", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Brink''s', 'Berend Jan van der Wal', 'CFO', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'AB Mauri', 'Bob Roks', 'Manager Financial Accounting & Reporting', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "laatst geweest", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Alliander', 'Camiel de Vries', 'Change manager a.i.', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'AKZO Nobel Car Refinishes', 'Chris Lin', 'EMEA Business Treasury', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'VORM Ontwikkeling', 'Christiaan van Steenbergen', 'CFO', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Hollandia Infra B.V.', 'Corvin Janssen', 'Business controller', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "Marc ook afspraak", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Deloitte Consulting', 'Deen Sonneveldt', 'Partner', 'Arno', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'oppartners.nl', 'Edwin Heeren', 'CFO', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "oppakken investeringsmaatschappij", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'CBOX Containers', 'Elco Diesbergen', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'minezk.nl', 'Ellen Thijert', 'co', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "Vrouw van Eric", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'TBI Holdings B.V.', 'Emiel Roozen', 'lid Raad van Bestuur', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, '', 'Emma Labas', 'Bestuur', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Amsterdam Commodities N.V.', 'Eric Smit', 'Director Projects', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Foppen Seafood', 'Eric Taal', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'United Rentals', 'Erik Koenraads', 'FD Europe', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "zevenbergse  hoek", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Bergman Clinics', 'Erik Meester', 'Group Director Finance Control', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Koppert NL', 'Erik-Jan Verdegaal', 'CFO', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Holland & Barrett', 'Floris Berkhout', 'CPO', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "collega van maarten", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Interstream Barging', 'Frank Bartels', 'CFO', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Kenbri', 'Frank Scholtes', 'CFO', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Nimco & Xsensible', 'Geert-Willem Koolhof', 'CFOO', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'ONE HUNDRED RESTROOMS', 'George Gleichman', 'CFO', 'Olaf', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'SolarDuck', 'Gerald Verweij', 'CFO', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "afspraak aan plannen met Arno", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Ivory Accounting & Ivory Assurance Services', 'Gerard Hanssen', 'Partner', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Monchy Food Company', 'Guido Bakker', 'Manager Finance Strategic Projects', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "zit in capele ad ijssel", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Salta Group', 'Han Stoop', 'CFO', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Actief Werkt', 'Hans Damhuis', 'CFO', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Roll Group', 'Hans van den Bosch', 'CFO', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Randstad Groep Nederland', 'Hans van Slooten', 'CFO Randstad Group Belgium', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Mobilae', 'Henrik-Jan Rinner', 'CFO', 'Sander', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "2026-07-30 00:00:00", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', NULL, 'Henry van der Geest', 'Directeur', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'CitizenM hotels', 'Hugo van den Ochtend', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'McCain Foods Holland B.V.', 'Huub Tholhuijsen', 'Finance Director', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Nationale Nederlanden', 'Jaco van der Meer', 'Changemanager Finance', 'Sander', 'Mail', 'Visit', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Welten Groep', 'Jan Willem Weidema', 'CFO', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "gaat golfen", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'ARCADIS Nederland BV', 'Jan-Oege Goslings', 'CFO Advisory and Digital Intelligence', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Sunweb Group', 'Jeroen de Swart', 'CFO', 'Olaf', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'PaymentGenes', 'Jeroen van Dijk', 'Managing Partner (en CFO)', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Damen Shipyards Group', 'John Jansen', 'Financieel directeur', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Feadship', 'John Veldman', 'CFO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Edco', 'Leendert van Reeuwijk', 'CFO', 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'BAM', 'Luurt van der Ploeg', 'CFO/COO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'OCI', 'M van der Heijden', 'Financieel Directeur', 'Joost', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'hollandandbarret.com', 'Maarten de Ridder', 'Head of Finance', 'Olaf', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Mecanoo', 'Maarten Postma', 'CFO', 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, NULL, 'Manon Quaedvlieg', 'CFO', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Atrium Agri', 'Marc Alblas', 'CFO', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Bouwcombinatie Nieuw-Zuid', 'Marc Euser', 'Financieel Directeur', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Gemeente Den Haag', 'Marc van der Bilt', 'Businesspartner Control SZW', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Centraal orgaan opvang asielzoekers', 'Marie-Louise Dibbets', 'Transitiemanager Finance & Control', 'Arno', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Detron', 'Mark Fait', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Jumbo Supermarkten B.V.', 'Mark van de Meulenhof', 'Manager Group Finance', 'Olaf', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "bezig met nieuwe baan", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Hes International BV', 'Mark van Lieshout', 'CFO', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Louw BV', 'Martijn van de Louw', 'CFO', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "zzp", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Jiffy Group', 'Martin Hes', 'CFO', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Van Dam Bodegraven B.V.', 'Michael Korthouwer', 'CFO', 'Olaf', 'Teams', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Human Protection', 'Mirko de Vos', 'CFO/COO', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Batenburg Techniek N.V.', 'Mitchell Lensselink', 'Controller', 'Arno', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Golfbaan Bentwoud', 'Onno Jacobs', 'Directeur', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'QuandaGo', 'Patrick van Eerden', 'CFO', 'Arno', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "MIchael Afspraak plannen", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Nimbus hands-on investors', 'Paul Frohn', 'Partner', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'schildmeijer.com', 'Paul Schildmeijer', 'Owner', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Louwman Groep', 'Paul van den Wittenboer', 'Programmamanager', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'MSO Group', 'Paul van der Zande', 'CFO', 'Olaf', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "Bezig met neuwe baan", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Chrysal Flower Food', 'PEPIJN Asselberghs', 'CFO', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, NULL, 'Peter Rinkes', 'CFO', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Combilo', 'Peter-Christian de Jong', 'CVO', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Rail Innovators Group', 'Philipp Belle', 'CFO', 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "Zeer frequent contact mee.", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Transavia Airlines C.V.', 'Pieter Wensveen', 'CFO', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Houweling Holding bv', 'Raymond Overweg', 'financieel directeur', 'Olaf', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'VDfinancialservices', 'Richard van Duijn', 'CFO', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Interstellar ICT', 'Rob Lanen', 'CFO', 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Keygene', 'Robbert Oudendijk', 'Group Finance Director', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Noordhoff Uitgevers', 'Robêrt De Gier', 'CFO / COO', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Plazapadel', 'Robert Melgerd', 'Nvt', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Acta Marine BV', 'Roel van Ess', 'CFO', 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "Arno", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Joh. Mourik & Co.', 'Ron Duijn', 'Financieel Directeur', 'Marc', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Holland Food Service', 'Roy Janssen', 'Financieel Directeur', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Flexible Human Services', 'Sander Guijt', 'Directeur Financiën & Organisatie', 'Arno', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'ANWB', 'Sandra Keessen', 'programma manager duurzaamheid/Finance', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Young Capital', 'Sebastiaan van Welie', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Laadsnel.nl', 'Serge van der Kruijk', 'Finance Director', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'de Volksbank', 'Sjoerd Meijer', 'Head of Finance Operations', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Spares in Motion', 'Thomas mattheussens', 'CFO', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Bol.com', 'Thomas Nulle', 'Finance Director', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Refresco', 'Tim Winkelhuis', 'Group M&A Manager', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-05-21", "text": "26 juni golf", "origin": "origineel"}]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Damen Shipyards Group', 'Ton Huggers', 'Finance Director', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', 'Nee', 'Vereniging Eigen Huis', 'Wietse de Heer', 'CFO', 'Olaf', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('21 Mei | CFO Open', NULL, 'Trivium Packaging', 'Willem Morkin', 'EU Finance Director', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, 'TNO', 'Susan Swarte', 'CFO', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-06-26", "text": "allergisch voor zwarte bessen (bosbessen en bramen zijn prima)", "origin": "origineel"}]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, 'Fugro', 'Barbara Geelen', 'CFO', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, 'Louwman', 'Lisanne Rijnders', 'CFO Automotive', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', 'Nee', 'Deerns', 'Esther van de Arend', 'CFO ', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', 'Nee', 'Walraven', 'Monique van Leeuwen', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, 'NSI', 'Elke Snijders', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', 'Nee', 'N-Sea', 'Ann Porte', 'CFO', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, 'McDonalds', 'Inge Hamilton', 'Head of Business Control', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-06-26", "text": "geen schaal/schelpdieren ivm allergie", "origin": "origineel"}]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, NULL, 'Mayte Oosterveld', 'CFO vml JustEat TakeAway', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, 'House of Redmore', 'Juliette Piree', 'CFO', 'Michael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', 'Nee', 'CleVR', 'Jolande Masen', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, 'HHS', 'Mignon de Ruiter', 'CFO', 'Arno', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, 'PreScan', 'Roelien Boezel-Pardijs', 'CFO', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, NULL, 'Cindy Smeele', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, NULL, 'Cissy Zandvliet', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('26 Jun | CFO Lunch', NULL, NULL, 'w', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Söderberg & Partners', 'Anton van Roon', 'Manager Finance & Control', 'Arno', 'Mail', NULL, 'Deta', NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Afspraak in de maak voor nieuwe verbinding", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Unica', 'Eric de Kruif', 'Group controller', 'Arno', 'Mail', NULL, 'Deta', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Agro Care Ontwikkeling B.V.', 'Eric Schouten', 'CFO', 'Arno', 'Visit', NULL, 'Deta', NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "2026-08-04 00:00:00", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Pels Rijcken & Droogleever Fortuijn N.V.', 'Erna Bakker', 'Hoofd Finance & Control', 'Arno', 'Visit', NULL, 'W&S', NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "2026-07-13 00:00:00", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Unica', 'Jeroen de Bree', 'Finance Director', 'Arno', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Afspraak in de maak om bij te praten", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Bergman Clinics', 'Klaas Rus', 'Manager Financiele administratie', 'Arno', 'Mail', NULL, 'AI', NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Afspraak in de maak voor AI", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'AFC Ajax', 'Annemarie Reynolds', 'Head of Finance', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Mail gestuurd naar Annemarie en opvolging via Sander Mesman.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'BridgeFund', 'Barry Den Blanken', 'Group controller', 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Visit ingepland op 16 juli.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Flora Food Group', 'Bart Commijs-Hayoz', 'Team Lead OTC Control Europe', 'Arno', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Oud agium en zijn bedrijf zit in Amsterdam, werkt zelf in zwitersland volgens mij. Arno kent hem volgens mij dus aangepast.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Econocom', 'Coos Rijneveld', 'CFO', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Mail gestuurd om bij te praten", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'CitizenM hotels', 'Cornelis Trommel', 'Global Manager Finance Operations', 'Joost', 'Visit', NULL, 'ABS', NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Afspraak 6 augustus", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Ahold Delhaize', 'Daan Kempers', 'Director CFO Office', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Afspraak om Visit te maken op de dag zelf gemaakt.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'McDonalds', 'Inge Hamilton', 'Finance director', 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Afspraak net geweest, richting einde van de zomer weer t.a.v. verlenging Odette.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'SnowWorld', 'ivo van Boven', 'manager Finance BeNeFra', 'Joost', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Vertrekt bij Snowworld, overdracht naar nieuwe manager in de maak.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Digital Realty Trust Inc', 'Lutfiyya Meniers', 'Director of Accounting', 'Joost', 'Call', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Afspraak gemaakt om bij te praten.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Postillion Hotels', 'Max Siem-A-Joe', 'CFO', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Visit in te plannen.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'VodafoneZiggo Group BV', 'Onno van Kesteren', 'Head of Finance Innovation', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Opvolging introductiemail MvA.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Lely Holding', 'Pauline Wernekinck', 'Group controller', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Werkt inmiddels bij Cosun, contact over naar Olaf.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Digital Realty Trust Inc', 'Pieter De Bruijn', 'VP Accounting EMEA', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Inzake verlenging  Chris Lieuw opgestart.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Akzo Nobel', 'Jarno Levinga', 'Finance Director IT, Commercial & Strategic Development and R&D', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Opvolging in te plannen d.m.v. Visit of Teams.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Stromma', 'Richard Brouwer', 'Finance Manager', 'Joost', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Amsterdam", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'McDonalds', 'Rik van Nimwegen', 'Sr. Transformation Manager', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "is dit een ZZP?", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Ajax', 'Sander Mesman', NULL, 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Opvolging in te plannen d.m.v. Visit of Teams.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Exact Software Nederland B.V.', 'Sander Smit', 'Finance Director', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Opvolging in te plannen d.m.v. Visit of Teams.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Schiphol Nederland B.V.', 'Tom Gerritsen', 'Director Finance', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Opvolging in te plannen d.m.v. Visit of Teams.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Postillion Hotels', 'Jurgen Bonapart', 'Head of Finance', 'Joost', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Opvolging in te plannen d.m.v. Visit of Teams.", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Joh. Mourik & Co.', 'Auke Droogh', 'Financieel Directeur', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Strukton', 'Patrick van der Linden', 'Director Corporate Reporting & Accounting', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'TNO', 'Paul ten Hout', 'Manager Unit Control', 'Marc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Alliander', 'Camiel de Vries', 'Change manager', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Verhinderd", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'CED Europe', 'Carmen Kaijser', 'Finance Manager NL', 'Olaf', NULL, 'Mail', NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'omniplast-group.com', 'Dirk van der Kant', 'Finance Director', 'Olaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "zit in veghel", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Stahl', 'Eric Brouwer', 'Group Director Controlling & Consolidation', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "vorige week langs geweest", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Primenutgroup', 'Florence van der Kooij', 'CFO', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "zeeland", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Jacobs Douwe Egberts NL B.V.', 'Frits van Zijdervelt', 'CFO Europe', 'Olaf', 'Visit', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "wordt ingepland", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Archipel Academy', 'Jack Swart', 'Finance Improvement Manager', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "onlangs afspraak gehad", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Heijmans', 'Jan De Leeuw', 'Head of Finance & Control', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Kapimex', 'Kim Vos', 'Finance Manager', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'VTTI b.v.', 'Madeleine den Ouden', 'Head of Group Reporting', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Afspraak in de maak", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Jumbo Supermarkten B.V.', 'Mark van de Meulenhof', 'Manager Group Finance', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "heeft gegolfd", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'CEVA Logistics', 'Martijn Melissant', 'Head of Finance', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "onlangs afspraak gehad met micheal", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Egala Zorg', 'Michel Boukens', 'Manager Finance & Control', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "breda", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'VTTI b.v.', 'Pan van Geffen', 'Group Controller and Deputy CFO', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "onlnags geweest", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Green Energy Storage', 'Paul van der Veen', 'CFO', 'Olaf', NULL, 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "van de week afspraak", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Hezelaer', 'Pim Flink', 'Head of Finance', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "gegolfd", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Heijmans', 'Richard Ossenblok', 'Financieel Directeur', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'DP World', 'Robin Fennis', 'Finance Director', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Refresco', 'Tim Winkelhuis', 'Group M&A Manager', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "staat afspraak mee", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Damen Shipyards Group', 'Ton Huggers', 'Finance Director', 'Olaf', 'Call', 'Visit', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Golfafspraak", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Vereniging Eigen Huis', 'Wietse de Heer', 'CFO | Sectormanager Bedrijfsvoering', 'Olaf', 'Visit', 'Mail', NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "net langs geweest", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Philips Personal Health', 'Wouter Mul', 'Head of Finance IT', 'Olaf', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Deerns', 'Esther van der Arend', 'CFO', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'ANWB', 'Jelle IJsselstijn', 'Directeur Group Finance', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Farmhouse International', 'Jill van Doorn', 'Financieel Directeur', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Poeldijk", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Dutch Flower Group', 'Jurjan ​​​​ van der Laarse', 'Managing Director Group Finance', 'Roberto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Pathé', 'Bart Van Rooij', 'CFO', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Louwman Groep', 'Douwe Bekenkamp', 'Financieel Directeur', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Last Mile Solutions B.V.', 'Groeneveld Corné', 'CFO', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Sarens', 'Marck De Heer', 'Finance Manager', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'HCS Groep B.V.', 'Mayra Werges', 'CFRO', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Volker Energy Solutions B.V.', 'Peter Houtman', 'Financieel Directeur', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Pathé', 'Renee Brand', 'Manager Accounting & Reporting', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'SGS Nederland B.V.', 'Richard Oostrom', 'Finance Director Benelux', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'NN', 'Stijn Neomagus', 'Change Controller Group IT', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Koole Tankstorage Minerals B.V.', 'Tim Osse', 'Manager Business Control', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Evides Drinkwater', 'Veronique Groenewegen', 'Manager Finance & Contracts', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', NULL, 'Mark Krijgsman', 'Finance director', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Komt Mark vanuit zijn nieuwe rol?", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Menzis', 'Martijn Stadig', 'Manager Business Control', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "wageningen", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'Yanmar Co., Ltd.', 'Maya Sing', 'Finance Transformation Specialist', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Almere ziten", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', NULL, 'Young Capital', 'Paula Groen in ''t Woud', 'Group Controller', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Hoofddorp", "origin": "origineel"}]'::jsonb),
  ('02 Jul | Future CFO', 'Nee', 'CycloVriend', 'Sascha Vos', 'Business controller', 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": "2026-07-02", "text": "Amersfoort", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'Your Surprise', 'Bram Buis', 'CFO', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'IHC', 'Bert-Jaap Dijkstra', 'CFO', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Westlake Chemical', 'Jaap Schilder', 'Finance manager', 'Olaf', 'call', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Catom/OK Nederland', 'Bart Hontele', 'CFO', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Daelmans', 'Nick Verhaaren', 'CFO', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'McCain Foods Holland B.V.', 'Huub ', 'CFO', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Marten en van Oord', 'Peter Maartsen', 'Finance manager', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'JR infra', 'Kees Kraaijeveld', 'HR Directeur', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Van der Lande', 'Mark Roeters', 'Domein Controller', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'VEH', 'Wietse  de Heer', 'CFO/Sectormanager Bedrijfsvoering', 'Olaf', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Certhon', 'Dennis Zwinkels', 'Finance Director', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Sandvik', 'Alex Balkhoven', 'Finance Manager', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Deerns', 'Esther van der Arend', 'CFO', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Atrium Agri', 'Marc Alblas', 'CFO', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'ANP', 'Gert-Jan STrik', 'CFO', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'ASG', 'Jolanda Cortlever ', 'Management Consultant', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'NLRealty', 'Roy Boutkan', 'CFO', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Husqvarna ', 'Cock de Nijs', 'CFO', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Aon', 'Erik van der Niet', 'Manager Business Control', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Zpot', 'Eefke Visser', 'CEO', 'Roberto', 'afspraak', NULL, 'Boek', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Equans', 'Robert Melkert', 'Manager Finance & Control', 'Arno', 'afspraak', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'QuandaGo International B.V.', 'Patrick van Eerden', 'CFO', 'Arno', 'afspraak', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Pels Rijcken', 'Erna Bakker', 'Manager Finance & Control', 'Arno', 'mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Charlie Works', 'Niels van Dorsten', 'Manager Finance & Control', 'Arno', 'afspraak', NULL, 'Afspraak', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Worley', 'Boris de Wilde', 'Head of Project Accounting', 'Arno', 'mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'AEG Power Solutions', 'Marco Krommendijk', 'CFO', 'Arno', 'mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'FHS', 'Sander Guijt', 'CFO', 'Arno', 'mail', NULL, 'Afspraak', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Varo Energy', 'René Smaal', 'CFO', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Vopak', 'Sander van der Water', 'Senior Vice President Finance and Procurement', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Louwman', 'Floor van der Laarse', 'Group Control Director', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Afspraak", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'Nederlandse Hartstichting', 'Theo Stolze', 'CFO', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Olympia', NULL, NULL, 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'The Greenery', NULL, NULL, 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Stora Enso', 'Fazıl Bölükbaş', 'Head of Controlling', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Xiver', 'Bas Pijnenburg', 'Interim CFO', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Woonstad Rotterdam', 'Paula Esmoris Gomez', 'Manager Administraties F&C', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Lyreco Group', 'Francois Dieleman', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Den Hartogh ', 'Jeroen Visser', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Verpact', 'Toby bergshoef', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'CBR', 'Randall van Hoey Smith', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Samenwerkende Kinderopvang', 'Sander Boehlé', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Dael Groep', 'Twann Verhoeven', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Afspraak", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'Food&I', 'Roy Rebens', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Afspraak", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'Cometec', 'Yorick Limburg', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Total Energies', 'Lorenzo Langeveld', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Geen interesse", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'van Ameyde', 'Maurice Snoek', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'CMA CGM', 'Hans-Peter Drinkwaard', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Equinix', 'Bram Koole', NULL, 'Sander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Isero ', 'Wilco van Izerloo', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Woonzorg Nederland', 'René Wallenburg', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Afspraak", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'HEMA', 'Gertjan van den Eijkel', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Duynie Groep', 'Marieke van Eijk', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'IDEXX ', 'Manfred Birekhoven', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Isero ', 'Angela van Os', NULL, 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Ingram Micro', 'Karolien Gijsen', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Afspraak", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'Mobilae', 'Henrik-Jan Rinner', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Afspraak", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'WZH', 'Maarten van Brandwijk', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'The Greenery', 'Carl Wijnveldt', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Afspraak", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'Toyota Louwman', 'Franjo Huyghe', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[{"ts": null, "text": "Afspraak", "origin": "origineel"}]'::jsonb),
  ('Boekactie', NULL, 'Zeeman', 'John Morsink', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Salta Group', 'Han Stoop', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Juva', 'Annelieke Blaauboer', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Liquin', 'Linda Kraakman', NULL, 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Nationale Nederlanden', 'Victor Thijs', 'Manager Finance & Administration', 'Sander', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Nationale Nederlanden', 'Vincent van Meeuwen', 'Senior Project & Finance Manager', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Nationale Nederlanden', 'Marnix Blok', 'Manager Finance & Administration', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Nationale Nederlanden', 'Remco Mulder', 'Head of Finance Transformation & Reporting', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Nationale Nederlanden', 'Robert van den Akker', 'Project Manager Finance', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Nationale Nederlanden', ' Tatjana Wester Djuricic', 'Sr. Manager Finance Control', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Nationale Nederlanden', 'Anne den Besten', 'Finance Business Partner', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Nationale Nederlanden', ' Joyce Derksen', 'Manager Business Control NN Bank', 'Sander', 'Linkedin', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'NWO', 'Hans van Zwol', 'Manager Project Control', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'EUR (FSSB)', 'Bram Suithoff', 'Directeur Bedrijfsvoering', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'N-SEA', 'Miet van Maegdenberg', 'Manager Financial Control', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'TU Delft', 'Hans de jager', 'Manager F&C', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Van Wijnen', 'Stephan Arens', 'Manager Financial Control', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Dura vermeer', 'Bart Spierings', 'Manager Finance  & Control', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Dura vermeer', 'Nico Dufrenne', 'Manager Finance  & Control', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Atom', 'Jaco Robben', 'Manager Finance  & Control', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Strukton', 'Jacco Vos', 'Project Controller', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Mourik Infra', 'Jeroen Liefhebber', 'FD', 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Heijmans', 'Richard Osseblok', NULL, 'Marc', 'Mail', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'McDonalds', 'Inge Hamilton', NULL, 'Joost', 'Afspraak 2-6', NULL, 'Afgeleverd', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'McDonalds', 'Rik Boijmans', NULL, 'Joost', 'Afspraak 2-6', NULL, 'Afgeleverd', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Schiphol', 'Yvette van den Broek', NULL, 'Joost', 'Afspraak 3-6', NULL, 'Afgeleverd', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Schiphol', 'Amar Arjun Sharma', NULL, 'Joost', 'Afspraak 3-6', NULL, 'Afgeleverd', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'AS Operations', 'Cornelis Trommel', NULL, 'Joost', 'Afspraak 3-6', NULL, 'Afgeleverd', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Snowworld', 'Ivo van Boven', NULL, 'Joost', 'Afspraak verzet', NULL, 'Afspraak online geworden', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Visma', 'Esther van der Meer', NULL, 'Joost', 'Afspraak 29-6', NULL, 'Afgeleverd', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Home Fashion Group', 'Bas Luiten', NULL, 'Joost', 'Afspraak 24-6', NULL, 'Afspraak online geworden', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'Ymere', 'Chester Bal', NULL, 'Joost', 'Aspraak 24-6', NULL, 'Afgeleverd', NULL, NULL, NULL, NULL, '[]'::jsonb),
  ('Boekactie', NULL, 'PF Concept', 'Sander de Mutstert', NULL, 'Joost', 'Afspraak in de maak', NULL, NULL, NULL, NULL, NULL, NULL, '[]'::jsonb);